eureka:
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://localhost:9090/eureka/
server:
   port: 9090
   
   
zuul:
  prefix: /api
  routes:
    ms1-person:
      path: /ms1-person/**
      url: http://localhost:9091
    ms2-user:
      path: /ms1-user/**
      url: http://localhost:9092